return {
	{ import = "plugins.bufferLine" }, -- Browser like buffers
	{ import = "plugins.ccc" }, -- color picker
	{ import = "plugins.cmp" }, -- Text completion
	{ import = "plugins.colorizer" },
	{ import = "plugins.conform" }, -- Code formater
	{ import = "plugins.dressing" }, -- Ui enhancements
	{ import = "plugins.entireFile" }, -- For selecting entire file
	{ import = "plugins.flash" }, -- Better navigation
	{ import = "plugins.gitSigns" }, -- Github signs in file
	{ import = "plugins.lazyGit" }, -- Lazy git
	{ import = "plugins.luaLine" }, -- Status line
	{ import = "plugins.markdownPreview" }, -- Markdown redenring
	{ import = "plugins.marks" }, -- Marks
	{ import = "plugins.mason" }, -- install lsp
	{ import = "plugins.mdmath" }, -- Math rendering
	{ import = "plugins.mini" }, -- A collection of mini plugins
	{ import = "plugins.neoScroll" }, -- For scmooth scrolling
	{ import = "plugins.noice" },
	{ import = "plugins.obsidian" }, -- Obsidian.md support
	{ import = "plugins.oil" }, -- File explorer
	-- { import = "plugins.persistence" },
	{ import = "plugins.rainbowDelimiters" },
	{ import = "plugins.remote" }, -- ssh remote
	{ import = "plugins.renderMarkdown" },
	{ import = "plugins.snacks" }, -- Many small plugins
	{ import = "plugins.superMaven" }, -- AI code completion
	{ import = "plugins.tabOut" }, -- Use tab for navigation
	{ import = "plugins.telescope" }, -- Fuzzy finder
	{ import = "plugins.theme" }, -- Theme
	{ import = "plugins.treeSitter" }, -- Code parser
	-- { import = "plugins.todoComments" }, -- Todo comments
	{ import = "plugins.toggleCheckboxes" }, -- Checkboxes
	{ import = "plugins.ufo" }, -- Code folding
	{ import = "plugins.undoTree" }, -- Better undos
	{ import = "plugins.vimTex" }, -- Tex support
	{ import = "plugins.vsnip" }, -- Snippets
	{ import = "plugins.w3m" }, -- Web browser
	{ import = "plugins.webDevIcons" }, -- Web icons
	{ import = "plugins.whichKey" }, -- Keymaps menu
	{ import = "plugins.winShift" }, -- Keymaps menu
	{ import = "plugins.zen" }, -- Zen mode
}
