return {
	-- { import = "plugins.aerial" }, -- Keymaps menu
	-- { import = "plugins.betterGoToFile" }, -- Browser like buffers
	-- { import = "plugins.bigfile" },
	-- { import = "plugins.biscuits" }, -- Better debugging
	-- { import = "plugins.codex" }, -- Codex
	-- { import = "plugins.copilot" }, -- Supermaven replement
	-- { import = "plugins.dap" }, -- Better debugging
	-- { import = "plugins.dapMason" },
	-- { import = "plugins.dapui" },
	-- { import = "plugins.entireFile" }, -- For selecting entire file
	-- { import = "plugins.flash" }, -- Better navigation
	-- { import = "plugins.lazyGit" }, -- Lazy git
	-- { import = "plugins.livePreview" },
	-- { import = "plugins.markdownPreview" }, -- Markdown redenring
	-- { import = "plugins.markdownTable" }, -- Markdown table formatter
	-- { import = "plugins.marks" }, -- Marks
	-- { import = "plugins.mdPdf" },                 -- Browser like buffers
	-- { import = "plugins.mdmath" }, -- Math rendering
	-- { import = "plugins.mini" }, -- A collection of mini plugins
	-- { import = "plugins.neoScroll" }, -- For scmooth scrolling
	-- { import = "plugins.netrw" },
	-- { import = "plugins.noice" },
	-- { import = "plugins.notify" },
	-- { import = "plugins.obsidian" },              -- Obsidian.md support
	-- { import = "plugins.obsidianNew" }, -- Obsidian.md support
	-- { import = "plugins.persistence" },
	-- { import = "plugins.playground" },
	-- { import = "plugins.precognition" }, -- Show keymaps in buffer for easy navigation
	-- { import = "plugins.pywal16" },               -- Colorscheme
	-- { import = "plugins.remote" }, -- ssh remote
	-- { import = "plugins.snacks" },      -- Many small plugins
	-- { import = "plugins.superMaven" }, -- SUNSETED AI code completion
	-- { import = "plugins.todoComments" }, -- Todo comments
	-- { import = "plugins.toggleCheckboxes" }, -- Checkboxes
	-- { import = "plugins.treeSitterTextObjects" }, -- Code parser
	-- { import = "plugins.undoTree" }, -- Better undos
	-- { import = "plugins.venn" }, -- Better debugging
	-- { import = "plugins.vimTex" }, -- Tex support
	-- { import = "plugins.vsnip" }, -- Snippets
	-- { import = "plugins.w3m" }, -- Web browser
	-- { import = "plugins.webDevIcons" }, -- Web icons
	-- { import = "plugins.winShift" }, -- Window management
	-- { import = "plugins.zen" }, -- Zen mode

	{ import = "plugins.lsp" }, -- LSP
	{ import = "plugins.bufferLine" }, -- Browser like buffers
	{ import = "plugins.cmp" }, -- Text completion
	{ import = "plugins.colorizer" }, -- Colorcode highlight
	{ import = "plugins.conform" }, -- Code formatter
	{ import = "plugins.dressing" }, -- Ui enhancements
	{ import = "plugins.gitSigns" }, -- Github signs in file
	{ import = "plugins.luaLine" }, -- Status line
	{ import = "plugins.luasnip" }, -- Snippets
	{ import = "plugins.mason" }, -- install lsp
	{ import = "plugins.oil" }, -- File explorer
	{ import = "plugins.rainbowDelimiters" }, -- Rainbow delimiters
	{ import = "plugins.renderMarkdown" },
	{ import = "plugins.tabOut" }, -- Use tab for navigation
	{ import = "plugins.telescope" }, -- Fuzzy finder
	{ import = "plugins.theme" }, -- Theme
	{ import = "plugins.treeSitter" }, -- Code parser
	{ import = "plugins.treesj" },
	{ import = "plugins.ufo" }, -- Code folding
	{ import = "plugins.whichKey" }, -- Keymaps menu
}
