return {
	-- {"neanias/everforest-nvim"},
	-- {"AlexvZyl/nordic.nvim"},
	-- {"LunarVim/synthwave84.nvim"},
	-- {"Matsuuu/pinkmare"},
	-- {"TroyFletcher/vim-colors-synthwave"},
	-- {"bluz71/vim-moonfly-colors"},
	-- {"bluz71/vim-nightfly-colors"},
	-- {"catppuccin/nvim"},
	-- {"jacoborus/tender.vim"},
	-- {"kepano/flexoki"},
	-- {"mcchrish/vim-no-color-collections"},
	-- {"myxik/lovelace.nvim"},
	-- {"navarasu/onedark.nvim"},
	-- {"nyoom-engineering/nyoom.nvim"},
	-- {"nyoom-engineering/oxocarbon.nvim"},
	-- {"olimorris/onedarkpro.nvim"},
	-- {"olivercederborg/poimandres.nvim"},
	-- {"rebelot/kanagawa.nvim"},
	-- {"rmehri01/onenord.nvim"},
	-- {"rose-pine/neovim"},
	-- {"sainnhe/edge"},
	-- {"savq/melange-nvim"},
	{ "folke/tokyonight.nvim" },
	{ "EdenEast/nightfox.nvim" },
	{ "projekt0n/github-nvim-theme" },
	{ "gmr458/vscode_modern_theme.nvim" },
	{ "Mofiqul/vscode.nvim" },
	{ "serhez/teide.nvim" },
	{ "oskarnurm/koda.nvim" },
	{ "bluz71/vim-moonfly-colors" },
}
