return {
  { "folke/tokyonight.nvim" },
  { "neanias/everforest-nvim" },
  {"AlexvZyl/nordic.nvim"},
  {"bluz71/vim-moonfly-colors"},
  {"bluz71/vim-nightfly-colors"},
  {"catppuccin/nvim"},
  {"jacoborus/tender.vim"},
  {"kepano/flexoki"},
  {"LunarVim/synthwave84.nvim"},
  {"mcchrish/vim-no-color-collections"},
  {"myxik/lovelace.nvim"},
  {"navarasu/onedark.nvim"},
  {"nyoom-engineering/nyoom.nvim"},
  {"nyoom-engineering/oxocarbon.nvim"},
  {"olimorris/onedarkpro.nvim"},
  {"olivercederborg/poimandres.nvim"},
  {"rebelot/kanagawa.nvim"},
  {"rmehri01/onenord.nvim"},
  {"sainnhe/edge"},
  {"savq/melange-nvim"},
  {"TroyFletcher/vim-colors-synthwave"},
  {"Matsuuu/pinkmare"},
  {"rose-pine/neovim"},

}
