vim.keymap.set("n", "n", "<Nop>")
vim.keymap.set("n", "N", "<Nop>")
vim.keymap.set("n", "e", "<Nop>")
vim.keymap.set("n", "E", "<Nop>")

return {
	{
		"nvim-treesitter/nvim-treesitter",
		dependencies = {
			"nvim-treesitter/nvim-treesitter-textobjects",
			"nvim-treesitter/playground",
		},
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"css",
					"html",
					"javascript",
					"python",
					"latex",
					"scss",
					"tsx",
					"markdown",
				},
				sync_install = true,
				auto_install = true,
				ignore_install = { "" },
				modules = {},
				highlight = {
					enable = true,
				},
				textobjects = {
					select = {
						enable = true,
						lookahead = true,
						keymaps = {
							["af"] = "@function.outer",
							["ac"] = "@class.outer",
							["al"] = "@loop.outer",
							["ap"] = "@parameter.outer",
							["ai"] = "@conditional.outer",
							["ar"] = "@return.outer",
							["aa"] = "@assignment.outer",
							["as"] = "@statement.outer",
							["am"] = "@comment.outer",
							["ab"] = "@block.outer",
							["if"] = "@function.inner",
							["ic"] = "@class.inner",
							["il"] = "@loop.inner",
							["ip"] = "@parameter.inner",
							["ii"] = "@conditional.inner",
							["ir"] = "@return.inner",
							["ia"] = "@assignment.inner",
							["is"] = "@statement.inner",
							["im"] = "@comment.inner",
							["ib"] = "@block.inner",
						},
					},
					move = {
						enable = true,
						set_jumps = true,
						goto_next_start = {
							["nf"] = "@function.outer",
							["nc"] = "@class.outer",
							["nl"] = "@loop.outer",
							["np"] = "@parameter.outer",
							["ni"] = "@conditional.outer",
							["nr"] = "@return.outer",
							["na"] = "@assignment.outer",
							["ns"] = "@statement.outer",
							["nm"] = "@comment.outer",
							["nb"] = "@block.outer",
						},
						goto_previous_start = {
							["Nf"] = "@function.outer",
							["Nc"] = "@class.outer",
							["Nl"] = "@loop.outer",
							["Np"] = "@parameter.outer",
							["Ni"] = "@conditional.outer",
							["Nr"] = "@return.outer",
							["Na"] = "@assignment.outer",
							["Ns"] = "@statement.outer",
							["Nm"] = "@comment.outer",
							["Nb"] = "@block.outer",
						},
						goto_next_end = {
							["ef"] = "@function.outer",
							["ec"] = "@class.outer",
							["el"] = "@loop.outer",
							["ep"] = "@parameter.outer",
							["ei"] = "@conditional.outer",
							["er"] = "@return.outer",
							["ea"] = "@assignment.outer",
							["es"] = "@statement.outer",
							["em"] = "@comment.outer",
							["eb"] = "@block.outer",
						},
						goto_previous_end = {
							["bf"] = "@function.outer",
							["bc"] = "@class.outer",
							["bl"] = "@loop.outer",
							["bp"] = "@parameter.outer",
							["bi"] = "@conditional.outer",
							["br"] = "@return.outer",
							["ba"] = "@assignment.outer",
							["bs"] = "@statement.outer",
							["bm"] = "@comment.outer",
							["bb"] = "@block.outer",
						},
					},
				},
			})
		end,
	},
}
